### ISSUE TITLE
Store metadata about collections in vdir

### ISSUE THREAD

**Issue by mistotebe** [untitaker/vdirsyncer#125]
When performing discovery, vdirsyncer requests the calendar name (displayname), but that is never propagated anywhere. It would be useful to have that name stored alongside the calendar, which would also help the synchronization process as the calendar/addressbook name could then be copied over along its entries.

**Comment by hobarrera** [comment]
> Using .displayname and .color files would be the way to go IMO. Both are UTF8 encoded.

I like the idea of having the displayname and colour in files, but I don't see a need for them to be dotfiles. Merely `displayname` and `colour`is ok (and does not conflict with the current vdir spec).

> The .color file would contain a six-char hexcode.
> Applications like khal would have to support reading color and calendar name, otherwise this would be useless. Not sure how khal would translate hexcodes to valid terminal colorcodes though.

I'd opt to using some library that deals with this functionality. Remember that different terminals may have different colour capabilites (16 colours, 256 colours, etc), so there's a need to round the colour to the closest thing available in terminals (I dislike the idea of limiting ourselves to those colours only because it limits functionality for non-terminal apps).

---

Not sure how we'd deal the the colour been synced. I know that displayname is a calendar property, but do we have custom properties we can use to store the colour?

**Comment by untitaker** [comment]
>I like the idea of having the displayname and colour in files, but I
>don't see a need for them to be dotfiles. Merely `displayname` and
>`colour`is ok (and does not conflict with the current vdir spec).
>

That's fine too.

>I'd opt to using some library that deals with this functionality.
>Remember that different terminals may have different colour capabilites
>(16 colours, 256 colours, etc), so there's a need to round the colour
>to the closest thing available in terminals (I dislike the idea of
>limiting ourselves to those colours only because it limits
>functionality for non-terminal apps).

I think we should encode colors as rgb value (e.g. hexcode) because otherwise graphical applications will loose this metadata when unable to express their whole colorspace.

Terminal applications can round to the nearest colorcode. The reverse (encoding to a rgb value that would round down to a specific colorcode) should also be possible.

Regarding the implementation: You might want to take a look at colorama, and at the various image renderers that exist for the terminal (since those have to round down color values too)

>Not sure how we'd deal the the colour been synced. I know that
>displayname is a calendar property, but do we have custom properties we
>can use to store the colour?
>

Yes, it's pretty standard.

**Comment by hobarrera** [comment]
> I think we should encode colors as rgb value (e.g. hexcode) because otherwise graphical applications will loose this metadata when unable to express their whole colorspace.

>Terminal applications can round to the nearest colorcode. The reverse (encoding to a rgb value that would round down to a specific colorcode) should also be possible.

That's what I meant.

[python-colour](https://github.com/vaab/colour) doesn't seem to be of use (for clients like khal), regrettably. Dunno if there's something already done to round rgb -> term. [colorama](https://github.com/tartley/colorama) doesn't seem to take rgb as an input, so I don't think it'll be of use either (someone might want to double check this last one).

**Comment by untitaker** [comment]
The ansi package on pypi seems to be capable of this. There seems to be an algorithm in there for converting to the nearest escape sequence too.

**Comment by untitaker** [comment]
colorama still is useful for Windows compat (it can convert ansi output to Win32 calls)

**Comment by untitaker** [comment]
[todoman](https://git.barrera.io/hobarrera/todoman/) by @hobarrera now reads the color of a collection from a `color` file. The [metadata](https://github.com/untitaker/vdirsyncer/tree/metadata) branch on vdirsyncer documents how the format looks like.

**Comment by untitaker** [comment]
I have a rudimentary version with one-way sync running at https://github.com/untitaker/vdirsyncer/pull/227.

I'm not sure if it's a good idea to implement two-way sync.

**Comment by hobarrera** [comment]
IMHO we need two-way sync, because otherwise we don't have how to alter the value on the DAV side (at least not via vdir-clients).

**Comment by untitaker** [comment]
Done. I'd merge this as-is, please try.

**Comment by untitaker** [comment]
This will be released in 0.6, the docs are somewhat sparse but will be expanded "on demand".
