### ISSUE TITLE
plain passwords in .collections status files + metadata vs. calendar names

### ISSUE THREAD

**Issue by petr-fischer** [untitaker/vdirsyncer#213]
Hello - my questions:

1) in the ~/.vdirsyncer/status folder, there is *.collections cache files - but there is plain passwords in it - why? Isn't it a bad idea? 

2) I syncing apple icloud calendars, but instead of calendar names i have folders like "7A552FEA-3BBD-4379-92A7-D7C268DDA909" under ~/.calendars - there is a human readable names of calendars inside the *.collections file under ~/.vdirsyncer/status - are this collections files the right place, where to read real calendar name (collection_human field) from?

3) iCloud calendars have more metadata like "color" - is it supported?

Thanks very much! (I don't know, if mailing lists exists somewhere)

**Comment by untitaker** [comment]
>in the ~/.vdirsyncer/status folder, there is *.collections cache files - but there is plain passwords in it - why? Isn't it a bad idea? 

Those are only there if you already have set the password in plaintext in your config file. So in the end there's not much difference security-wise: People who can access your files have your password, whether it's copied to the `*.collections` files or now.

What worries me is that the user might set wrong permissions on those files because they underestimate their sensibility. I guess I'll push a commit for that anyway...

>are this collections files the right place, where to read real calendar name (collection_human field) from?
>iCloud calendars have more metadata like "color" - is it supported?

Metadata isn't exposed by vdirsyncer yet. See #125.
