### ISSUE TITLE
Searching ~/.contacts

### ISSUE THREAD

**Issue by kaihendry** [untitaker/vdirsyncer#247]
I looked through the docs and I was wondering how to integrate the VCF files with mutt or any other contact lookup paradigm.

Currently I'm just grepping ~/.contacts. Is that the way?

Or am I missing something?  Related to #145

**Comment by benjaminfrank** [comment]
You might want to look at https://github.com/scheibler/khard/

**Comment by kaihendry** [comment]
I don't quite understand the relationship between vdirsyncer & khard.

Should I be using khard to query my local trove of VCF files or should I just be using khard?

**Comment by benjaminfrank** [comment]
khard queries a local folder containing you vcf files, while vdirsyncer keeps this firectory synced with your carddav server

**Comment by kaihendry** [comment]
How does vdirsyncer in practice keeped synced? A cronjob? Or does khard call it ?

**Comment by benjaminfrank** [comment]
khard doesn't keep anything synced, it simply searches a folder of vcf files.
you need to run vdirsyncer either manually or per cronjob. there was also something about a daemon mode, but i didn't follow up on that one.

**Comment by untitaker** [comment]
For the daemon mode see #24, but you'll still have to launch vdirsyncer (through autostart or the OS' init system). Push sync or anything like that is unsupported, you'll have to do it yourself by stitching e.g. `inotifywait` and `vdirsyncer` to together.

Keep in mind that email addresses and name properties come in many different formats, depending on which software you used to create those contacts. Coming up with a regex that matches all formats is pretty hard, so to avoid reinventing the wheel, use khard, which uses a real vcf parser. For a few alternatives to khard see https://vdirsyncer.readthedocs.org/en/stable/supported.html

I'll close this since it seems your questions are answered. Feel free to open further issues for concrete suggestions about the documentation.
