### ISSUE TITLE
Relicense?

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#253]
The Mozilla Public License (https://www.mozilla.org/MPL/2.0/FAQ.html) seems like a perfect middle-ground between GPL and BSD.

The MIT license was always too permissive for me, however, what has always disturbed me about the GPL is its virality, which makes companies reinvent the wheel because GPL-licensed software effectively prevents them from creating an *internal* fork. It seems the MPL has solved that problem.

**Comment by untitaker** [comment]
Note that this is just a thought-experiment, I'm not really sure about this. Basically what I'd like to do is restrict how third parties may monetize vdirsyncer, at the same time I don't think it's a good idea for people to reinvent the wheel. Perhaps it's too late for that decision.

**Comment by hobarrera** [comment]
I fear that opening up for discussion will result in the endless debate that generally surrounds these topics.

Personally, I don't mind the openness of MIT. I'm not sure how popular picking up MPL code is in closed-software-world, and that may be a relevant thing to find out to see if you'd be helping to avoid reinvention of the wheel or not.

But in the end, IMHO, it should be the core developer(s) that make this decision.

**Comment by untitaker** [comment]
I think I'd have to ask all contributors if they're fine with it:

@t-8ch @geier @hobarrera @three-comrades @vimbaer @pierg75 @mathstuf @mondonc @tribut Are you fine with your contributions being relicensed under the MPL?

**Comment by mathstuf** [comment]
While I'm fine with MPLv2 in general, the motivations seem to be based on some wrong assumptions here.

> which makes companies reinvent the wheel because GPL-licensed software effectively prevents them from creating an internal fork.

False. If you don't have the binary, you aren't entitled to the source. I can patch the kernel all day long, but if I don't give you the binary, you can't request the source (this is the hole AGPLv3 patched with SaaS). Companies shying away from GPL software for internal use due to the virality have bad and/or overly skittish lawyers.

**Comment by untitaker** [comment]
Thanks for clarifying that, I'm still looking through this legal jungle. However, there are still some likable differences between the MPL and the GPL (if I understood them correctly):

* If you copypaste code from vdirsyncer into your application, the GPL would require you to publish that software under the GPL. The MPL and the LGPL don't require you to do that. The reason I don't like that is due to reinventing the wheel.
* However, if you fork vdirsyncer, you're only obligated to publish the sourcecode if you publish the binary.
* The MPL is basically like the LGPL, but has a more liberal definition of linking than the LGPL.

I'm still not sure if anything in the MPL matters to enforce the kind of usage I percieve to be "fair".

**Comment by mathstuf** [comment]
MPLv2 is copyleft, but at the file level, not the project level. AFAIU, any modifications to the source code must be provided, but not necessarily the files they reference (so "import foo; foo.install_hooks()" must be released, but not foo itself). LGPL is like GPL except that instead of the entire stack needing source, the LGPL bits must have their modifications released and replaceable in the resulting binary (hence, "don't static link to LGPL bits" but shared linking is fine since you can drop in a new library you compiled yourself). Of course, IANAL; Fedora's [wiki section on licensing](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing) is very helpful.

**Comment by untitaker** [comment]
>the LGPL bits must have their modifications released and replaceable in the resulting binary

Right, effectively this means you can link your proprietary code to LGPL only dynamically, not statically I think.

**Comment by untitaker** [comment]
I guess I'm postponing this indefinitely, I haven't made up my mind yet.

**Comment by geier** [comment]
I herewith agree to a relicensing of my contributions to vdirsyncer under any OSI approved open source license, including the MPL. 

Am 12. August 2015 17:42:39 MESZ, schrieb Markus Unterwaditzer <notifications@github.com>:

**Comment by t-8ch** [comment]
I herewith agree to a relicensing of my contributions to vdirsyncer under any OSI approved open source license, including the MPL. Now or in the future until further notice at this location.

**Comment by three-comrades** [comment]
Same for me: I herewith agree to a relicensing of my contributions to vdirsyncer under any OSI approved open source license, including the MPL. Now or in the future until further notice at this location.

**Comment by vimbaer** [comment]
I herewith agree to a relicensing of my contributions to vdirsyncer under any OSI approved open source license, including the MPL. Now or in the future until further notice at this location.

**Comment by untitaker** [comment]
I now think this whole issue is pointless. I'm fine with the MIT.

Sorry for the noise.
